---
abstract: 'Track Perl module and test relationships so you can guess what are the best tests to run.'
author:
  - 'dmorton and nnutter'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: TestTracker
requires:
  Carp: '0'
  Cwd: '0'
  DBI: '0'
  Data::UUID: '0'
  File::Basename: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  Getopt::Long: '0'
  IO::File: '0'
  IPC::Open3: '0'
  IPC::System::Simple: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Memoize: '0'
  POSIX: '0'
  Pod::Usage: '0'
  Symbol: '0'
  Test::Builder::Module: '0'
  Test::More: '0'
  YAML: '0'
  autodie: '0'
  base: '0'
  lib: '0'
  strict: '0'
  warnings: '0'
version: '0.037'
